#!/bin/bash

DATE=`date +%Y%m%d`

VSN=2.0.9

cd ..

case "$1" in
    ipkg) 
        tar czvf errdb/errdb-$VSN-$DATE-$1.tgz \
            errdb/README.md \
            errdb/ebin \
            errdb/bin errdb/etc \
            errdb/log errdb/var \
            errdb/lib/elog/ebin \
            errdb/lib/extlib/ebin \
            errdb/lib/lager/ebin \
            errdb/lib/mochiweb/ebin  \
            errdb/lib/evmon/ebin
        ;;
    upkg) 
        tar czvf errdb/errdb-$VSN-$DATE-$1.tgz \
            errdb/ebin \
            errdb/bin \
            errdb/lib/elog/ebin \
            errdb/lib/extlib/ebin \
            errdb/lib/lager/ebin \
            errdb/lib/mochiweb/ebin  \
            errdb/lib/evmon/ebin
        ;;
    *)
        echo "Usage: $SCRIPT {ipkg | upkg}"
        ;;
esac

exit 0

